#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: //donavon.west

# Your name
author: Donavon West

# Short bio or description (displayed in the header)
description: Just some Internets guy and champion of all things JavaScript

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/887639

# A favicon for your site. The URL is relative to your {{ site.url }}.
favicon:
  url: images/256px-JavaScript-logo.png
  type: image/png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: js@donavon.com
  facebook: donavon
  flickr:
  github: donavon
  instagram: donavonwest
  linkedin: donavon
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: donavon
  stackoverflow: users/2517449/donavon # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: donavongithubio

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-79986575-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://donavon.js.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji
  - jekyll-mentions

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

defaults:
  -
    values:
      layout: "post"
      author: "donavon"

prose:
  rooturl: '_posts'
  siteurl: 'http://donavon.js.org/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "author"
        field:
          element: "text"
          label: "Author"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          value: false
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
